#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-avx-tools
Version  : 2
Release  : 2
URL      : https://github.com/clearlinux/clr-avx-tools/archive/v2.tar.gz
Source0  : https://github.com/clearlinux/clr-avx-tools/archive/v2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: clr-avx-tools-bin
Requires: clr-avx-tools-license
BuildRequires : cmake

%description
No detailed description available

%package bin
Summary: bin components for the clr-avx-tools package.
Group: Binaries
Requires: clr-avx-tools-license

%description bin
bin components for the clr-avx-tools package.


%package license
Summary: license components for the clr-avx-tools package.
Group: Default

%description license
license components for the clr-avx-tools package.


%prep
%setup -q -n clr-avx-tools-2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530563943
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1530563943
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/clr-avx-tools
cp COPYING %{buildroot}/usr/share/doc/clr-avx-tools/COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/avxjudge.py
/usr/bin/clr-avx2-move.pl
/usr/bin/clr-python-avx2
/usr/bin/clr-python-avx512

%files license
%defattr(-,root,root,-)
/usr/share/doc/clr-avx-tools/COPYING
